"use client";

import { useState } from "react";
import { cn } from "@/lib/utils";
import { Icon } from "@/components/qbit/primitives/Icon";
import { SurfaceCard } from "@/components/qbit/primitives/GlassCard";
import { QbitButton } from "@/components/qbit/primitives/QbitButton";
import { SectionHeader } from "@/components/qbit/dashboard/SectionHeader";
import { SEO_CONFIGS } from "@/lib/cms/placeholder-data";

/**
 * SEOEditor — auto-generates SEO metadata with manual override capability.
 * Shows slug, title, description, keywords, OG image, canonical URL,
 * and JSON-LD structured data.
 */
export function SEOEditor() {
  const [selectedId, setSelectedId] = useState(SEO_CONFIGS[0]?.id ?? "");
  const selected = SEO_CONFIGS.find((s) => s.id === selectedId);
  const [autoGen, setAutoGen] = useState(selected?.autoGenerated ?? true);

  return (
    <section className="space-y-4">
      <SectionHeader title="SEO Management" accentDot />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Entity list */}
        <SurfaceCard className="p-3 lg:col-span-1">
          <p className="text-[10px] font-bold uppercase tracking-wider text-qbit-on-surface-variant mb-2 px-1">Entities</p>
          <div className="space-y-1">
            {SEO_CONFIGS.map((config) => (
              <button
                key={config.id}
                onClick={() => { setSelectedId(config.id); setAutoGen(config.autoGenerated); }}
                className={cn(
                  "flex items-center gap-2 w-full p-2 rounded-lg text-left transition-colors",
                  selectedId === config.id ? "bg-qbit-primary/10 text-qbit-primary" : "hover:bg-qbit-surface-container-low text-qbit-on-surface-variant",
                )}
              >
                <Icon name={config.entityType === "product" ? "inventory_2" : "article"} className="text-[16px]" />
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-medium truncate">/{config.slug}</p>
                  <p className="text-[10px] capitalize">{config.entityType}</p>
                </div>
                {config.autoGenerated ? (
                  <Icon name="auto_awesome" className="text-[14px] text-qbit-outline" />
                ) : (
                  <Icon name="edit" className="text-[14px] text-qbit-primary" />
                )}
              </button>
            ))}
          </div>
        </SurfaceCard>

        {/* Editor */}
        <SurfaceCard className="p-5 lg:col-span-2">
          {selected && (
            <div className="space-y-4">
              {/* Auto-generate toggle */}
              <div className="flex items-center justify-between pb-3 border-b border-qbit-outline-variant/40">
                <div>
                  <p className="text-sm font-semibold text-qbit-on-surface">SEO Configuration</p>
                  <p className="text-xs text-qbit-on-surface-variant">/{selected.slug}</p>
                </div>
                <label className="flex items-center gap-2 cursor-pointer">
                  <span className="text-xs text-qbit-on-surface-variant">Auto-generate</span>
                  <button
                    onClick={() => setAutoGen(!autoGen)}
                    className={cn("relative w-9 h-5 rounded-full transition-colors", autoGen ? "bg-qbit-primary" : "bg-qbit-outline-variant")}
                  >
                    <span className={cn("absolute top-0.5 w-4 h-4 rounded-full bg-white transition-transform", autoGen ? "left-4" : "left-0.5")} />
                  </button>
                </label>
              </div>

              {/* Slug */}
              <div>
                <label className="block text-xs font-semibold text-qbit-on-surface-variant mb-1">URL Slug</label>
                <div className="flex items-center gap-2">
                  <span className="text-xs text-qbit-outline whitespace-nowrap">/products/</span>
                  <input
                    type="text"
                    defaultValue={selected.slug}
                    disabled={autoGen}
                    className="flex-1 rounded-lg border border-qbit-outline-variant bg-qbit-surface-container-low px-3 py-2 text-sm disabled:opacity-60 focus:bg-white focus:ring-2 focus:ring-qbit-primary/40 focus:border-qbit-primary"
                  />
                  <button aria-label="Check availability" className="flex h-9 w-9 items-center justify-center rounded-lg border border-qbit-outline-variant text-qbit-on-surface-variant hover:text-qbit-primary">
                    <Icon name="verified" className="text-[16px]" />
                  </button>
                </div>
                {autoGen && <p className="text-[10px] text-qbit-outline mt-1 flex items-center gap-1"><Icon name="auto_awesome" className="text-[12px]" /> Auto-generated from product name</p>}
              </div>

              {/* Title */}
              <div>
                <label className="block text-xs font-semibold text-qbit-on-surface-variant mb-1">Meta Title <span className="text-qbit-outline normal-case">({selected.title?.length ?? 0}/60)</span></label>
                <input type="text" defaultValue={selected.title} disabled={autoGen} className="w-full rounded-lg border border-qbit-outline-variant bg-qbit-surface-container-low px-3 py-2 text-sm disabled:opacity-60 focus:bg-white focus:ring-2 focus:ring-qbit-primary/40 focus:border-qbit-primary" />
              </div>

              {/* Description */}
              <div>
                <label className="block text-xs font-semibold text-qbit-on-surface-variant mb-1">Meta Description <span className="text-qbit-outline normal-case">({selected.description?.length ?? 0}/160)</span></label>
                <textarea rows={2} defaultValue={selected.description} disabled={autoGen} className="w-full rounded-lg border border-qbit-outline-variant bg-qbit-surface-container-low px-3 py-2 text-sm disabled:opacity-60 focus:bg-white focus:ring-2 focus:ring-qbit-primary/40 focus:border-qbit-primary resize-y" />
              </div>

              {/* Keywords */}
              <div>
                <label className="block text-xs font-semibold text-qbit-on-surface-variant mb-1">Keywords</label>
                <div className="flex flex-wrap gap-1.5">
                  {selected.keywords?.map((kw) => (
                    <span key={kw} className="inline-flex items-center gap-1 text-[11px] bg-qbit-surface-container-high px-2 py-0.5 rounded-full text-qbit-on-surface-variant">
                      {kw}
                      {!autoGen && <button className="text-qbit-outline hover:text-red-500"><Icon name="close" className="text-[10px]" /></button>}
                    </span>
                  ))}
                  {!autoGen && <button className="text-[11px] text-qbit-primary hover:underline">+ Add keyword</button>}
                </div>
              </div>

              {/* Canonical URL */}
              <div>
                <label className="block text-xs font-semibold text-qbit-on-surface-variant mb-1">Canonical URL</label>
                <input type="url" defaultValue={selected.canonicalUrl} disabled={autoGen} className="w-full rounded-lg border border-qbit-outline-variant bg-qbit-surface-container-low px-3 py-2 text-sm disabled:opacity-60 focus:bg-white focus:ring-2 focus:ring-qbit-primary/40 focus:border-qbit-primary" />
              </div>

              {/* JSON-LD indicator */}
              <div className="flex items-center gap-2 text-xs text-qbit-on-surface-variant pt-2 border-t border-qbit-outline-variant/40">
                <Icon name="code" className="text-[16px] text-qbit-primary" />
                JSON-LD structured data: <span className="text-emerald-600 font-semibold">Auto-generated (Product + BreadcrumbList)</span>
              </div>

              {!autoGen && (
                <div className="flex justify-end gap-2 pt-2">
                  <QbitButton size="sm" variant="outline">Reset to Auto</QbitButton>
                  <QbitButton size="sm" variant="primary" icon="save">Save SEO</QbitButton>
                </div>
              )}
            </div>
          )}
        </SurfaceCard>
      </div>
    </section>
  );
}
