/**
 * GET /api/downloads/[id]/file — serve the actual download file
 *
 * In production, this would redirect to a cloud-storage signed URL.
 * For now, it serves a generated placeholder file so the download
 * workflow completes end-to-end.
 */

import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth/options";
import type { Role } from "@/lib/rbac/roles";

interface Params {
  params: Promise<{ id: string }>;
}

export async function GET(req: NextRequest, { params }: Params) {
  const { id } = await params;
  const url = new URL(req.url);
  const token = url.searchParams.get("token");

  if (!token) {
    return NextResponse.json({ error: "Missing download token" }, { status: 401 });
  }

  try {
    const download = await db.download.findUnique({
      where: { id },
      include: { category: true },
    });

    if (!download) {
      return NextResponse.json({ error: "Download not found" }, { status: 404 });
    }

    // Check visibility
    if (download.visibility === "internal" || download.visibility === "restricted") {
      const session = await getServerSession(authOptions);
      if (!session?.user) {
        return NextResponse.json({ error: "Authentication required" }, { status: 401 });
      }
      if (download.visibility === "restricted") {
        const role = session.user.role as Role;
        if (role !== "administrator" && role !== "installation_engineer") {
          return NextResponse.json({ error: "Access denied" }, { status: 403 });
        }
      }
    }

    // Generate a placeholder file (in production: redirect to cloud storage signed URL)
    const fileName = `${download.name.replace(/\s+/g, "_")}_v${download.version}.txt`;
    const fileContent = `QBIT Hub Download
====================
File: ${download.name}
Version: ${download.version}
Category: ${download.category.name}
Size: ${download.fileSize} bytes
Checksum: ${download.checksum ?? "N/A"}
Release Date: ${download.releaseDate.toISOString()}

This is a placeholder file generated by QBIT Hub.
In production, this endpoint would redirect to a cloud-storage signed URL
(Supabase Storage, AWS S3, or UploadThing) serving the actual binary file.

Download ID: ${download.id}
Token: ${token}
Timestamp: ${new Date().toISOString()}
`;

    return new NextResponse(fileContent, {
      status: 200,
      headers: {
        "Content-Type": "text/plain",
        "Content-Disposition": `attachment; filename="${fileName}"`,
        "Content-Length": fileContent.length.toString(),
      },
    });
  } catch (error) {
    console.error("[API ERROR] GET /api/downloads/[id]/file:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
