/**
 * Typed interfaces for the Production Data Management & CMS module.
 */

/** Import job types. */
export type ImportType = "product" | "driver" | "manual" | "category" | "youtube" | "image" | "document";
export type ImportStatus = "pending" | "previewing" | "importing" | "completed" | "failed" | "rolled_back";

/** Import job entry. */
export interface ImportJobEntry {
  id: string;
  type: ImportType;
  fileName: string;
  fileSize: string;
  status: ImportStatus;
  totalRows: number;
  successCount: number;
  errorCount: number;
  errors?: string[];
  startedBy: string;
  startedAt: string;
  completedAt?: string;
  createdAt: string;
}

/** Import preview row (parsed data before commit). */
export interface ImportPreviewRow {
  rowNumber: number;
  status: "valid" | "warning" | "error";
  message?: string;
  data: Record<string, string>;
}

/** Content version entry. */
export interface ContentVersionEntry {
  id: string;
  entityType: string;
  entityId: string;
  version: number;
  changedBy: string;
  changeSummary?: string;
  createdAt: string;
  canRestore: boolean;
}

/** Media file entry. */
export interface MediaFileEntry {
  id: string;
  fileName: string;
  originalName: string;
  mimeType: string;
  fileSize: string;
  folder: string;
  tags: string[];
  usageCount: number;
  uploadedBy: string;
  createdAt: string;
  thumbnailUrl?: string;
  icon: string;
}

/** SEO configuration entry. */
export interface SEOConfigEntry {
  id: string;
  entityType: string;
  entityId: string;
  slug: string;
  title?: string;
  description?: string;
  keywords?: string[];
  ogImage?: string;
  canonicalUrl?: string;
  autoGenerated: boolean;
}

/** QR mapping entry. */
export interface QRMappingEntry {
  id: string;
  entityType: string;
  entityId: string;
  qrType: string;
  targetUrl: string;
  qrImageUrl: string;
  downloadCount: number;
  createdAt: string;
}

/** Export job entry. */
export interface ExportJobEntry {
  id: string;
  type: string;
  format: "csv" | "xlsx";
  rowCount: number;
  fileSize: string;
  status: "completed" | "processing" | "failed";
  createdBy: string;
  createdAt: string;
  downloadUrl: string;
}

/** Import wizard step. */
export type ImportStep = "upload" | "preview" | "validate" | "importing" | "complete";

/** YouTube import row. */
export interface YouTubeImportRow {
  url: string;
  videoId: string;
  title: string;
  category: string;
  featured: boolean;
  displayOrder: number;
  visibility: "public" | "internal" | "hidden";
}
