/**
 * Admin SEO API — `/api/admin/seo`.
 * GET: list SEO configurations (admin only).
 * PUT: update SEO configuration (admin only).
 */

import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth/options";
import { db } from "@/lib/db";
import { log } from "@/lib/monitoring/logger";
import { sanitizeText, validateRequired } from "@/lib/security/validation";
import { badRequest, forbidden, internalError } from "@/lib/errors/handler";

export async function GET(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session?.user || session.user.role !== "administrator") return forbidden();

  const { searchParams } = new URL(req.url);
  const entityType = searchParams.get("entityType");

  const where = entityType ? { entityType } : {};

  try {
    const configs = await db.sEOConfiguration.findMany({
      where,
      orderBy: { updatedAt: "desc" },
      take: 100,
    });
    return NextResponse.json({ configs, total: configs.length });
  } catch (err) {
    return internalError(err as Error, { route: "seo-list" });
  }
}

export async function PUT(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session?.user || session.user.role !== "administrator") return forbidden();

  const body = await req.json();
  const { id, slug, title, description, keywords, ogImage, canonicalUrl, jsonLd, autoGenerated } = body;
  const missing = validateRequired(body, ["id", "slug"]);
  if (missing.length > 0) return badRequest(`Missing fields: ${missing.join(", ")}`);

  try {
    // Check for duplicate slug
    const existing = await db.sEOConfiguration.findFirst({
      where: { slug: sanitizeText(slug, 200), NOT: { id } },
    });
    if (existing) return badRequest("Slug already in use by another entity");

    // Save slug history if slug changed
    const current = await db.sEOConfiguration.findUnique({ where: { id: sanitizeText(id, 50) } });
    if (current && current.slug !== slug) {
      await db.slugHistory.create({
        data: {
          entityType: current.entityType,
          entityId: current.entityId,
          oldSlug: current.slug,
          newSlug: sanitizeText(slug, 200),
        },
      });
    }

    const config = await db.sEOConfiguration.update({
      where: { id: sanitizeText(id, 50) },
      data: {
        slug: sanitizeText(slug, 200),
        title: title ? sanitizeText(title, 200) : null,
        description: description ? sanitizeText(description, 500) : null,
        keywords: keywords ? JSON.stringify(keywords) : null,
        ogImage: ogImage ? sanitizeText(ogImage, 500) : null,
        canonicalUrl: canonicalUrl ? sanitizeText(canonicalUrl, 500) : null,
        jsonLd: jsonLd ? sanitizeText(jsonLd, 5000) : null,
        autoGenerated: Boolean(autoGenerated),
      },
    });
    log.info("SEO configuration updated", { seoId: config.id, slug: config.slug, user: session.user.id });
    return NextResponse.json({ config });
  } catch (err) {
    return internalError(err as Error, { route: "seo-update" });
  }
}
